trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        arm-android:
          TARGET: arm-linux-androideabi
        aarch64-android:
          TARGET: aarch64-linux-android
        i686-android:
          TARGET: i686-linux-android
        x86_64-android:
          TARGET: x86_64-linux-android
        x86_64:
          TARGET: x86_64-unknown-linux-gnu
        i686:
          TARGET: i686-unknown-linux-gnu
        arm:
          TARGET: arm-unknown-linux-gnueabi
        aarch64:
          TARGET: aarch64-unknown-linux-gnu
        x86_64-musl:
          TARGET: x86_64-unknown-linux-musl
        x86_64-mingw:
          TARGET: x86_64-pc-windows-gnu
        asmjs:
          TARGET: asmjs-unknown-emscripten

        x86_64-beta:
          TARGET: x86_64-unknown-linux-gnu
          TOOLCHAIN: beta
        x86_64-nightly:
          TARGET: x86_64-unknown-linux-gnu
          TOOLCHAIN: nightly

  - job: macOS
    pool:
      vmImage: macos-10.13
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64:
          TARGET: x86_64-apple-darwin
        i686:
          TARGET: i686-apple-darwin

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        # Seems to be failing for weird reasons...
        # i686-msvc:
        #   TARGET: i686-pc-windows-msvc
        #   RUSTFLAGS: -Ctarget-feature=-crt-static
        #   NAME: i686-msvc
        i686-msvc-static:
          TARGET: i686-pc-windows-msvc
          RUSTFLAGS: -Ctarget-feature=+crt-static
          NAME: i686-msvc-static
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc
          RUSTFLAGS: -Ctarget-feature=-crt-static
          NAME: x86_64-msvc
        x86_64-msvc-static:
          TARGET: x86_64-pc-windows-msvc
          RUSTFLAGS: -Ctarget-feature=+crt-static
          NAME: x86_64-msvc-static
